services:
  simcc-admin-db:
    image: pgvector/pgvector:pg17
    volumes:
      - simcc-admin-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  simcc-cache:
    image: redis:latest
    volumes:
      - simcc-cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  simcc-admin-back:
    image: gleidsoncosta/simcc-admin-back:${SIMCC_ADMIN_TAG}
    environment:
      CACHE_URL: redis://simcc-cache:6379/0
      PROXY_URL: http://simcc-admin-back-old:8000
      DATABASE_URL: postgresql://postgres:postgres@simcc-admin-db:5432/postgres
    env_file: .env
    depends_on:
      simcc-admin-db:
        condition: service_healthy
      simcc-cache:
        condition: service_healthy
    restart: unless-stopped

  simcc-admin-back-old:
    image: gleidsoncosta/simcc-admin-back-old:${SIMCC_ADMIN_OLD_TAG}
    environment:
      DATABASE_URL: postgresql://postgres:postgres@simcc-admin-db:5432/postgres
    env_file: .env
    depends_on:
      simcc-admin-db:
        condition: service_healthy
      simcc-cache:
        condition: service_healthy
    restart: unless-stopped

volumes:
  simcc-admin-db:
  simcc-cache: